version: '3'

tasks:
  compile:
    desc: Compile Ink story to JSON
    silent: true
    cmds:
      - |
        echo "---- Compiling Ink story to JSON"
        echo "./bin/inklecate -o build/story.json -j src/main.ink"
        if ./bin/inklecate -o build/story.json -j src/main.ink; then
          echo "✅ Compilation complete! Refresh your browser."
        else
          echo ""
          echo "❌ Compilation failed. Fix errors and save to retry."
        fi

  serve:
    desc: Start web server for development
    silent: true
    cmds:
      - |
        echo "---- Starting web server for development."
        echo "cd build && python3 -m http.server 8000"
        echo "Press Ctrl+C to stop"
        cd build && python3 -m http.server 8000
    interactive: true

  watch:
    desc: Watch for changes and auto-compile
    silent: true
    cmds:
      - |
        echo "---- Watching src/ for changes..."
        echo "Press Ctrl+C to stop"
        
        # Initial compile
        task compile
        
        # Watch for changes (requires inotify-tools on Linux)
        if command -v inotifywait >/dev/null 2>&1; then
          while inotifywait -e modify,create,delete -r src/ --exclude='.*\.swp$' 2>/dev/null; do
            echo "📝 Changes detected, recompiling..."
            task compile
          done
        else
          echo "❌ inotify-tools not found."
          echo "Run 'task setup:watch' to install it."
        fi
    interactive: true

  dev:
    desc: Start development environment (watch + serve)
    deps: [watch, serve]

  clean:
    desc: Clean build directory
    silent: true
    cmds:
      - |
        echo "---- Cleaning build directory"
        echo "rm -f build/story.json"
        rm -f build/story.json
        echo "Done"

  setup:
    desc: Install inklecate compiler
    silent: true
    cmds:
      - |
        echo "---- Setting up inklecate compiler..."
        if [ -f "./bin/inklecate" ]; then
          echo "✅ inklecate already installed"
        else
          echo "📦 Installing inklecate..."
          mkdir -p bin
          cd bin
          wget -q https://github.com/inkle/ink/releases/latest/download/inklecate_linux.zip
          unzip inklecate_linux.zip
          rm -rf inklecate_linux.zip
          cd ..
        fi
        chmod +x ./bin/inklecate
        echo "Done. Run 'task setup:watch' if you need file watching (requires sudo)."

  setup:watch:
    desc: Install inotify-tools for file watching (requires sudo)
    silent: true
    cmds:
      - |
        echo "---- Installing inotify-tools..."
        if command -v inotifywait >/dev/null 2>&1; then
          echo "✅ inotify-tools already installed"
          exit 0
        fi
        if command -v apt-get >/dev/null 2>&1; then
          sudo apt-get update && sudo apt-get install -y inotify-tools
        elif command -v dnf >/dev/null 2>&1; then
          sudo dnf install -y inotify-tools
        else
          echo "❌ Unknown package manager. Install inotify-tools manually."
          exit 1
        fi
        echo "✅ inotify-tools installed"

  build:
    desc: Build story for production
    cmds:
      - task clean
      - task compile
      - echo "Production build complete."

  help:
    desc: Show available tasks
    cmds:
      - task --list

  default:
    desc: Default task - start development environment
    cmds:
      - task dev
